import re


class DailingCodes:
    """
    This class contains a dictionary of phone number patterns and their corresponding country names. 
    The patterns are regular expressions (regex) that match the beginning of a phone number for a given country.
    """
    
    phone_number_patterns = {
    re.compile(r"^93\d{9}$"): "Afghanistan",
    re.compile(r"^355\d{9}$"): "Albania",
    re.compile(r"^213\d{9}$"): "Algeria",
    re.compile(r"^1684\d{7}$"): "American Samoa",
    re.compile(r"^376\d{8}$"): "Andorra",
    re.compile(r"^244\d{9}$"): "Angola",
    re.compile(r"^1264\d{7}$"): "Anguilla",
    re.compile(r"^672\d{8}$"): "Antarctica",
    re.compile(r"^1268\d{7}$"): "Antigua and Barbuda",
    re.compile(r"^54\d{10}$"): "Argentina",
    re.compile(r"^374\d{8}$"): "Armenia",
    re.compile(r"^297\d{7}$"): "Aruba",
    re.compile(r"^61\d{9}$"): "Australia",
    re.compile(r"^43\d{11}$"): "Austria",
    re.compile(r"^994\d{9}$"): "Azerbaijan",
    re.compile(r"^1242\d{7}$"): "Bahamas",
    re.compile(r"^973\d{8}$"): "Bahrain",
    re.compile(r"^880\d{9}$"): "Bangladesh",
    re.compile(r"^1246\d{7}$"): "Barbados",
    re.compile(r"^375\d{9}$"): "Belarus",
    re.compile(r"^32\d{9}$"): "Belgium",
    re.compile(r"^501\d{8}$"): "Belize",
    re.compile(r"^229\d{8}$"): "Benin",
    re.compile(r"^1441\d{7}$"): "Bermuda",
    re.compile(r"^975\d{8}$"): "Bhutan",
    re.compile(r"^591\d{8}$"): "Bolivia",
    re.compile(r"^387\d{8}$"): "Bosnia and Herzegovina",
    re.compile(r"^267\d{8}$"): "Botswana",
    re.compile(r"^55\d{11}$"): "Brazil",
    re.compile(r"^246\d{8}$"): "British Indian Ocean Territory",
    re.compile(r"^1284\d{7}$"): "British Virgin Islands",
    re.compile(r"^673\d{7}$"): "Brunei",
    re.compile(r"^359\d{9}$"): "Bulgaria",
    re.compile(r"^226\d{8}$"): "Burkina Faso",
    re.compile(r"^257\d{8}$"): "Burundi",
    re.compile(r"^855\d{9}$"): "Cambodia",
    re.compile(r"^237\d{8}$"): "Cameroon",
    re.compile(r"^1\d{10}$"): "Canada",
    re.compile(r"^238\d{8}$"): "Cape Verde",
    re.compile(r"^1345\d{7}$"): "Cayman Islands",
    re.compile(r"^236\d{8}$"): "Central African Republic",
    re.compile(r"^235\d{8}$"): "Chad",
    re.compile(r"^56\d{9}$"): "Chile",
    re.compile(r"^86\d{11}$"): "China",
    re.compile(r"^61\d{9}$"): "Christmas Island",
    re.compile(r"^61\d{9}$"): "Cocos Islands",
    re.compile(r"^57\d{10}$"): "Colombia",
    re.compile(r"^269\d{8}$"): "Comoros",
    re.compile(r"^682\d{7}$"): "Cook Islands",
    re.compile(r"^506\d{8}$"): "Costa Rica",
    re.compile(r"^385\d{8}$"): "Croatia",
    re.compile(r"^53\d{8}$"): "Cuba",
    re.compile(r"^599\d{8}$"): "Curacao",
    re.compile(r"^357\d{9}$"): "Cyprus",
    re.compile(r"^420\d{9}$"): "Czech Republic",
    re.compile(r"^243\d{9}$"): "Democratic Republic of the Congo",
    re.compile(r"^45\d{8}$"): "Denmark",
    re.compile(r"^253\d{8}$"): "Djibouti",
    re.compile(r"^1767\d{7}$"): "Dominica",
    re.compile(r"^1809\d{9}$"): "Dominican Republic",
    re.compile(r"^829\d{9}$"): "Dominican Republic (alternative)",
    re.compile(r"^849\d{9}$"): "Dominican Republic (alternative)",
    re.compile(r"^670\d{8}$"): "East Timor",
    re.compile(r"^593\d{9}$"): "Ecuador",
    re.compile(r"^20\d{9}$"): "Egypt",
    re.compile(r"^503\d{8}$"): "El Salvador",
    re.compile(r"^240\d{8}$"): "Equatorial Guinea",
    re.compile(r"^291\d{8}$"): "Eritrea",
    re.compile(r"^372\d{8}$"): "Estonia",
    re.compile(r"^251\d{9}$"): "Ethiopia",
    re.compile(r"^500\d{7}$"): "Falkland Islands",
    re.compile(r"^298\d{8}$"): "Faroe Islands",
    re.compile(r"^679\d{8}$"): "Fiji",
    re.compile(r"^358\d{9}$"): "Finland",
    re.compile(r"^33\d{9}$"): "France",
    re.compile(r"^689\d{8}$"): "French Polynesia",
    re.compile(r"^241\d{8}$"): "Gabon",
    re.compile(r"^220\d{8}$"): "Gambia",
    re.compile(r"^995\d{9}$"): "Georgia",
    re.compile(r"^49\d{10}$"): "Germany",
    re.compile(r"^233\d{9}$"): "Ghana",
    re.compile(r"^350\d{9}$"): "Gibraltar",
    re.compile(r"^30\d{10}$"): "Greece",
    re.compile(r"^299\d{8}$"): "Greenland",
    re.compile(r"^1473\d{7}$"): "Grenada",
    re.compile(r"^1671\d{7}$"): "Guam",
    re.compile(r"^502\d{8}$"): "Guatemala",
    re.compile(r"^441481\d{7}$"): "Guernsey",
    re.compile(r"^224\d{8}$"): "Guinea",
    re.compile(r"^245\d{8}$"): "Guinea-Bissau",
    re.compile(r"^592\d{8}$"): "Guyana",
    re.compile(r"^509\d{8}$"): "Haiti",
    re.compile(r"^504\d{8}$"): "Honduras",
    re.compile(r"^852\d{8}$"): "Hong Kong",
    re.compile(r"^36\d{9}$"): "Hungary",
    re.compile(r"^354\d{8}$"): "Iceland",
    re.compile(r"^91\d{10}$"): "India",
    re.compile(r"^62\d{10}$"): "Indonesia",
    re.compile(r"^98\d{10}$"): "Iran",
    re.compile(r"^964\d{9}$"): "Iraq",
    re.compile(r"^353\d{9}$"): "Ireland",
    re.compile(r"^441624\d{7}$"): "Isle of Man",
    re.compile(r"^972\d{9}$"): "Israel",
    re.compile(r"^39\d{10}$"): "Italy",
    re.compile(r"^225\d{8}$"): "Ivory Coast",
    re.compile(r"^1876\d{7}$"): "Jamaica",
    re.compile(r"^81\d{10}$"): "Japan",
    re.compile(r"^441534\d{7}$"): "Jersey",
    re.compile(r"^962\d{9}$"): "Jordan",
    re.compile(r"^7\d{10}$"): "Kazakhstan",
    re.compile(r"^254\d{9}$"): "Kenya",
    re.compile(r"^686\d{8}$"): "Kiribati",
    re.compile(r"^383\d{8}$"): "Kosovo",
    re.compile(r"^965\d{8}$"): "Kuwait",
    re.compile(r"^996\d{9}$"): "Kyrgyzstan",
    re.compile(r"^856\d{8}$"): "Laos",
    re.compile(r"^371\d{8}$"): "Latvia",
    re.compile(r"^961\d{9}$"): "Lebanon",
    re.compile(r"^266\d{8}$"): "Lesotho",
    re.compile(r"^231\d{8}$"): "Liberia",
    re.compile(r"^218\d{9}$"): "Libya",
    re.compile(r"^423\d{8}$"): "Liechtenstein",
    re.compile(r"^370\d{8}$"): "Lithuania",
    re.compile(r"^352\d{9}$"): "Luxembourg",
    re.compile(r"^853\d{8}$"): "Macau",
    re.compile(r"^389\d{8}$"): "North Macedonia",
    re.compile(r"^261\d{8}$"): "Madagascar",
    re.compile(r"^265\d{8}$"): "Malawi",
    re.compile(r"^60\d{9}$"): "Malaysia",
    re.compile(r"^960\d{7}$"): "Maldives",
    re.compile(r"^223\d{8}$"): "Mali",
    re.compile(r"^356\d{8}$"): "Malta",
    re.compile(r"^692\d{7}$"): "Marshall Islands",
    re.compile(r"^596\d{9}$"): "Martinique",
    re.compile(r"^222\d{8}$"): "Mauritania",
    re.compile(r"^230\d{8}$"): "Mauritius",
    re.compile(r"^52\d{10}$"): "Mexico",
    re.compile(r"^691\d{7}$"): "Micronesia",
    re.compile(r"^373\d{8}$"): "Moldova",
    re.compile(r"^377\d{8}$"): "Monaco",
    re.compile(r"^976\d{8}$"): "Mongolia",
    re.compile(r"^382\d{8}$"): "Montenegro",
    re.compile(r"^1664\d{7}$"): "Montserrat",
    re.compile(r"^212\d{9}$"): "Morocco",
    re.compile(r"^258\d{9}$"): "Mozambique",
    re.compile(r"^95\d{9}$"): "Myanmar",
    re.compile(r"^264\d{8}$"): "Namibia",
    re.compile(r"^674\d{7}$"): "Nauru",
    re.compile(r"^977\d{10}$"): "Nepal",
    re.compile(r"^31\d{9}$"): "Netherlands",
    re.compile(r"^64\d{9}$"): "New Zealand",
    re.compile(r"^505\d{8}$"): "Nicaragua",
    re.compile(r"^227\d{8}$"): "Niger",
    re.compile(r"^234\d{10}$"): "Nigeria",
    re.compile(r"^683\d{7}$"): "Niue",
    re.compile(r"^850\d{9}$"): "North Korea",
    re.compile(r"^47\d{8}$"): "Norway",
    re.compile(r"^968\d{8}$"): "Oman",
    re.compile(r"^92\d{10}$"): "Pakistan",
    re.compile(r"^680\d{7}$"): "Palau",
    re.compile(r"^507\d{8}$"): "Panama",
    re.compile(r"^675\d{8}$"): "Papua New Guinea",
    re.compile(r"^595\d{9}$"): "Paraguay",
    re.compile(r"^51\d{9}$"): "Peru",
    re.compile(r"^63\d{10}$"): "Philippines",
    re.compile(r"^48\d{9}$"): "Poland",
    re.compile(r"^1\d{10}$"): "Puerto Rico",
    re.compile(r"^974\d{8}$"): "Qatar",
    re.compile(r"^242\d{8}$"): "Republic of the Congo",
    re.compile(r"^262\d{9}$"): "Reunion",
    re.compile(r"^40\d{9}$"): "Romania",
    re.compile(r"^7\d{10}$"): "Russia",
    re.compile(r"^250\d{9}$"): "Rwanda",
    re.compile(r"^378\d{9}$"): "San Marino",
    re.compile(r"^239\d{8}$"): "Sao Tome and Principe",
    re.compile(r"^966\d{9}$"): "Saudi Arabia",
    re.compile(r"^221\d{8}$"): "Senegal",
    re.compile(r"^381\d{8}$"): "Serbia",
    re.compile(r"^248\d{7}$"): "Seychelles",
    re.compile(r"^232\d{8}$"): "Sierra Leone",
    re.compile(r"^65\d{8}$"): "Singapore",
    re.compile(r"^421\d{9}$"): "Slovakia",
    re.compile(r"^386\d{8}$"): "Slovenia",
    re.compile(r"^677\d{7}$"): "Solomon Islands",
    re.compile(r"^252\d{8}$"): "Somalia",
    re.compile(r"^27\d{9}$"): "South Africa",
    re.compile(r"^82\d{9}$"): "South Korea",
    re.compile(r"^34\d{9}$"): "Spain",
    re.compile(r"^94\d{10}$"): "Sri Lanka",
    re.compile(r"^249\d{9}$"): "Sudan",
    re.compile(r"^597\d{8}$"): "Suriname",
    re.compile(r"^46\d{9}$"): "Sweden",
    re.compile(r"^41\d{9}$"): "Switzerland",
    re.compile(r"^963\d{9}$"): "Syria",
    re.compile(r"^886\d{9}$"): "Taiwan",
    re.compile(r"^992\d{9}$"): "Tajikistan",
    re.compile(r"^255\d{9}$"): "Tanzania",
    re.compile(r"^66\d{9}$"): "Thailand",
    re.compile(r"^670\d{8}$"): "Timor-Leste",
    re.compile(r"^228\d{8}$"): "Togo",
    re.compile(r"^690\d{7}$"): "Tokelau",
    re.compile(r"^676\d{6}$"): "Tonga",
    re.compile(r"^1868\d{7}$"): "Trinidad and Tobago",
    re.compile(r"^216\d{8}$"): "Tunisia",
    re.compile(r"^90\d{10}$"): "Turkey",
    re.compile(r"^993\d{9}$"): "Turkmenistan",
    re.compile(r"^1\d{10}$"): "United States",
    re.compile(r"^44\d{10}$"): "United Kingdom",
    re.compile(r"^974\d{8}$"): "Qatar",
    re.compile(r"^262\d{8}$"): "Reunion",
    re.compile(r"^40\d{10}$"): "Romania",
    re.compile(r"^7\d{10}$"): "Russia",
    re.compile(r"^250\d{9}$"): "Rwanda",
    re.compile(r"^590\d{8}$"): "Saint Barthelemy",
    re.compile(r"^590\d{8}$"): "Saint Martin",
    re.compile(r"^1784\d{7}$"): "Saint Vincent and the Grenadines",
    re.compile(r"^684\d{7}$"): "Samoa",
    re.compile(r"^378\d{8}$"): "San Marino",
    re.compile(r"^239\d{8}$"): "Sao Tome and Principe",
    re.compile(r"^966\d{9}$"): "Saudi Arabia",
    re.compile(r"^221\d{8}$"): "Senegal",
    re.compile(r"^381\d{8}$"): "Serbia",
    re.compile(r"^248\d{8}$"): "Seychelles",
    re.compile(r"^65\d{8}$"): "Singapore",
    re.compile(r"^421\d{9}$"): "Slovakia",
    re.compile(r"^386\d{8}$"): "Slovenia",
    re.compile(r"^677\d{8}$"): "Solomon Islands",
    re.compile(r"^252\d{8}$"): "Somalia",
    re.compile(r"^27\d{9}$"): "South Africa",
    re.compile(r"^82\d{10}$"): "South Korea",
    re.compile(r"^34\d{9}$"): "Spain",
    re.compile(r"^94\d{10}$"): "Sri Lanka",
    re.compile(r"^249\d{9}$"): "Sudan",
    re.compile(r"^597\d{8}$"): "Suriname",
    re.compile(r"^47\d{8}$"): "Svalbard and Jan Mayen",
    re.compile(r"^1\d{10}$"): "Trinidad and Tobago",
    re.compile(r"^66\d{9}$"): "Thailand",
    re.compile(r"^670\d{7}$"): "Tokelau",
    re.compile(r"^676\d{5}$"): "Tonga",
    re.compile(r"^216\d{8}$"): "Tunisia",
    re.compile(r"^90\d{10}$"): "Turkey",
    re.compile(r"^993\d{9}$"): "Turkmenistan",
    re.compile(r"^1\d{10}$"): "Turks and Caicos Islands",
    re.compile(r"^688\d{7}$"): "Tuvalu",
    re.compile(r"^256\d{9}$"): "Uganda",
    re.compile(r"^380\d{9}$"): "Ukraine",
    re.compile(r"^971\d{9}$"): "United Arab Emirates",
    re.compile(r"^44\d{10}$"): "United Kingdom",
    re.compile(r"^1\d{10}$"): "United States",
    re.compile(r"^598\d{8}$"): "Uruguay",
    re.compile(r"^998\d{9}$"): "Uzbekistan",
    re.compile(r"^678\d{8}$"): "Vanuatu",
    re.compile(r"^58\d{10}$"): "Venezuela",
    re.compile(r"^84\d{10}$"): "Vietnam",
    re.compile(r"^1\d{10}$"): "Virgin Islands",
    re.compile(r"^681\d{7}$"): "Wallis and Futuna",
    re.compile(r"^967\d{9}$"): "Yemen",
    re.compile(r"^260\d{9}$"): "Zambia",
    re.compile(r"^263\d{9}$"): "Zimbabwe",
    }
